// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4L9qM6hNYYkjoguUm2tKGoZeEPix7eLY',
    appId: '1:551684094833:web:745b85d3f9676480c154d0',
    messagingSenderId: '551684094833',
    projectId: 'mausam-romal',
    authDomain: 'mausam-romal.firebaseapp.com',
    storageBucket: 'mausam-romal.appspot.com',
    measurementId: 'G-QPPHLJKKQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_sZBA3B2NhbIMwUestTDRyg_RxboOfo',
    appId: '1:551684094833:android:46cd9378d97db0c1c154d0',
    messagingSenderId: '551684094833',
    projectId: 'mausam-romal',
    storageBucket: 'mausam-romal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLltrcLYyBCBfvLKmaCoDnWdgjKGEtCi8',
    appId: '1:551684094833:ios:8857d0a977db10e2c154d0',
    messagingSenderId: '551684094833',
    projectId: 'mausam-romal',
    storageBucket: 'mausam-romal.appspot.com',
    androidClientId: '551684094833-tgqkjucvtaam0dof818oji40h7r87v31.apps.googleusercontent.com',
    iosClientId: '551684094833-uunf0a4gh5guv58eoddjcsi4erhghh69.apps.googleusercontent.com',
    iosBundleId: 'com.example.mausam',
  );
}
